### ISSUE TITLE
Additional arguments for plotMissingValuesHeatmap()

### ISSUE THREAD

**Issue by skiaphrene** [fmicompbio/einprot#24]
It would be nice to have additional control over the ComplexHeatmap::Heatmap() call within einprot::plotMissingValuesHeatmap(), in particular clustering rows/columns, and showing row/column names. These could be passed as named arguments to the plotMissingValuesHeatmap() function, or for other functionality, as ... that is then passed on to Heatmap(). I don't expect these would need to have script-level settings, it would only be for the power-users...

**Comment by skiaphrene** [comment]
Additional idea: restrict MV heatmap to features with at least 1 MV.

**Comment by csoneson** [comment]
These are both now implemented in the current development version (`v0.9.6`)
* https://github.com/fmicompbio/einprot/commit/53ea30bfe6cde394b982f61846d3d0fd3bee13f1
* https://github.com/fmicompbio/einprot/commit/7a55f9dba3cfca42e4b31aaa8c247aabfd3aa6e2

Also the density imputation plots: 
* https://github.com/fmicompbio/einprot/commit/cb22206567a54a1097df848edab1b775051f2be2
